# Generated by Django 5.2.1 on 2025-05-21 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 14, 8, 27, 740087)),
        ),
    ]
