# Generated by Django 5.2.1 on 2025-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addrress',
            new_name='addrress1',
        ),
        migrations.AddField(
            model_name='profile',
            name='addrress2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
