# Generated by Django 5.2.1 on 2025-05-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_addrress_profile_addrress1_profile_addrress2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addrress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='addrress2',
            new_name='address2',
        ),
    ]
