# Generated by Django 5.2.1 on 2025-05-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile_old_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
