# Generated by Django 5.2.1 on 2025-05-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_address1_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_old_cart',
        ),
    ]
