# Generated by Django 5.2.1 on 2025-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(default='بدون شماره تلفن', max_length=15),
            preserve_default=False,
        ),
    ]
