# Generated by Django 5.2.1 on 2025-05-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_shippingaddress_shipping_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
    ]
