# Generated by Django 5.2.1 on 2025-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_ammount_paid_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
