# Generated by Django 5.2.1 on 2025-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(default='بدون ایمیل', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
